### ISSUE TITLE
Virtual Adapter not supported

### ISSUE THREAD

**Issue by sdbcs** [microsoft/Test-NetHLK#10]
The script calls get-netadapter with the switch _**-Physical**_ which rules out virtual network adapters. 

During HLK testing of a virtual network adapter (tap6-windows) this module is used in the test **NICSTrictPropertyValidation** and results in the test not passing as the virtual adapter is not recognized.

**Comment by dcuomo** [comment]
Hello @sdbcs - This test should not be required for virtual adapters. I would request an errata if this is required in your playlist.
