### ISSUE TITLE
*JumboPacket DisplayParameterType is long ?

### ISSUE THREAD

**Issue by sandilyabhagi** [microsoft/Test-NetHLK#5]
The test is expecting *JumboPacket DisplayParameterType to be long not 'int' as per documentation (https://docs.microsoft.com/en-us/windows-hardware/drivers/network/keywords-that-can-be-edited)
****** ERROR: [FAIL] *JumboPacket DisplayParameterType is -ge 2 and -lt 5

Is it expected to be long ?

**Comment by dcuomo** [comment]
Please file issues with Microsoft support. This is not a support vehicle.

**Comment by sandilyabhagi** [comment]
Thank you. I will file with support
