### ISSUE TITLE
*NumaNodeId NumericParameterMaxValue is 65535

### ISSUE THREAD

**Issue by sandilyabhagi** [microsoft/Test-NetHLK#6]
The test is expecting *NumaNodeId NumericParameterMaxValue as 65535 which is not inline with (https://docs.microsoft.com/en-us/windows-hardware/drivers/network/standardized-inf-keywords-for-rss)
<html>
<body>

NumaNodeId | Preferred NUMA node | Int | 65535 (Any node) | 0 | System specific - cannot exceed 65534
-- | -- | -- | -- | -- | --

</body>
</html>

*** ERROR: [FAIL] *NumaNodeId NumericParameterMaxValue is 65535

**Comment by sandilyabhagi** [comment]
The test is failing even the max value is set to 65535 for NumaNodeId

**Comment by sandilyabhagi** [comment]
> The test is failing even the max value is set to 65535 for NumaNodeId

The test passes even with 65535 only if DisplayParameterType -ge 2 and -lt 5 but this condition is not validated by Test-NetHLK

**Comment by dcuomo** [comment]
Please file issues with Microsoft support. This is not a support vehicle.
