### ISSUE TITLE
Win2K22 failures

### ISSUE THREAD

**Issue by sandilyabhagi** [microsoft/Test-NetHLK#7]
1. ****** ERROR: [FAIL] The in use NDIS version for adapter Ethernet 2 was below the required versionfor this OS (Required: 6.85; Actual: 6.82)
https://docs.microsoft.com/en-us/windows-hardware/drivers/network/introduction-to-ndis-6-83
Is 6.85 is an incremental update to 6.83 or any features are required to implement ?

2. *MaxRssProcessors DisplayParameterType is -ge 5 and -lt 5 => What should be the DisplayParameterType ? enum ?
****** ERROR: [FAIL] *MaxRssProcessors DisplayParameterType is -ge 5 and -lt 5
****** ERROR: [FAIL] *MaxRssProcessors NumericParameterBaseValue is
****** ERROR: [FAIL] *MaxRssProcessors NumericParameterStepValue is
****** ERROR: [FAIL] *MaxRssProcessors NumericParameterMinValue is -le

3. NumRSSQueues DefaultRegistryValue is 65535, is this like *NumaNodeId 65535 => (-1) ? What should be the Max queues ?
*NumRSSQueues NumericParameterMinValue is -le 0 => How to interpret 0 RSS Queues ? non-rss queues ?
****** ERROR: [FAIL] *NumRSSQueues DefaultRegistryValue is 65535
****** ERROR: [FAIL] *NumRSSQueues NumericParameterMaxValue is -ge 65535
****** ERROR: [FAIL] *NumRSSQueues NumericParameterMinValue is -le 0

4. What should be the values filled for NicSwitch parameters
https://docs.microsoft.com/en-us/windows-hardware/drivers/network/standardized-inf-keywords-for-sr-iov
Is Win2K22 is expecting other values than mentioned in the above document ?
****** ERROR: [FAIL] NicSwitch on name is
****** ERROR: [FAIL] NicSwitch SwitchType is

The same .inf is passing with Win2K19 but failing with Win2K22. Kindly update the doc accordingly.

**Comment by sandilyabhagi** [comment]
@dcuomo Can you please help.

**Comment by dcuomo** [comment]
Please file issues with Microsoft Support rather than on GitHub.

**Comment by tiatca4-ops** [comment]
> 1. ****** ERROR: [FAIL] The in use NDIS version for adapter Ethernet 2 was below the required versionfor this OS (Required: 6.85; Actual: 6.82)
>    https://docs.microsoft.com/en-us/windows-hardware/drivers/network/introduction-to-ndis-6-83
>    Is 6.85 is an incremental update to 6.83 or any features are required to implement ?
> 2. *MaxRssProcessors DisplayParameterType is -ge 5 and -lt 5 => What should be the DisplayParameterType ? enum ?
>    ****** ERROR: [FAIL] *MaxRssProcessors DisplayParameterType is -ge 5 and -lt 5
>    ****** ERROR: [FAIL] *MaxRssProcessors NumericParameterBaseValue is
>    ****** ERROR: [FAIL] *MaxRssProcessors NumericParameterStepValue is
>    ****** ERROR: [FAIL] *MaxRssProcessors NumericParameterMinValue is -le
> 3. NumRSSQueues DefaultRegistryValue is 65535, is this like *NumaNodeId 65535 => (-1) ? What should be the Max queues ?
>    *NumRSSQueues NumericParameterMinValue is -le 0 => How to interpret 0 RSS Queues ? non-rss queues ?
>    ****** ERROR: [FAIL] *NumRSSQueues DefaultRegistryValue is 65535
>    ****** ERROR: [FAIL] *NumRSSQueues NumericParameterMaxValue is -ge 65535
>    ****** ERROR: [FAIL] *NumRSSQueues NumericParameterMinValue is -le 0
> 4. What should be the values filled for NicSwitch parameters
>    https://docs.microsoft.com/en-us/windows-hardware/drivers/network/standardized-inf-keywords-for-sr-iov
>    Is Win2K22 is expecting other values than mentioned in the above document ?
>    ****** ERROR: [FAIL] NicSwitch on name is
>    ****** ERROR: [FAIL] NicSwitch SwitchType is
> 
> The same .inf is passing with Win2K19 but failing with Win2K22. Kindly update the doc accordingly.
